### ISSUE TITLE
"Ganga with cmake" does not work for new tools

### ISSUE THREAD

**Issue by bixel** [lhcb/second-analysis-steps#37]
I tried to use the [Ganga with cmake](https://lhcb.github.io/second-analysis-steps/01-ganga-with-cmake.html) tutorial to submit a job with a development application. It failed to `import` the some custom tools although they were defined within `InstallArea/blabla/python/Application/ApplicationConf.py`. It looks like the `PYTHONPATH` doesn't know about the modules. When I add `InstallArea/blabla/python` to it, at least a `SetupProject` + `gaudirun.py` works.

I don't know how ganga sets up the `PYTHONPATH` but maybe there is another workaround?

**Comment by alexpearce** [comment]
Are you using the same version of Ganga as in the tutorial? It would be useful to know if a version change broke the hack.

**Comment by bixel** [comment]
Yes, I used the same version. (Sorry for the delay)

**Comment by alexpearce** [comment]
I've heard that the most recent version(s) of Ganga new support CMake applications, as created with `lb-dev`. You can follow up at ganga-devs/ganga#73.

**Comment by bixel** [comment]
Ok I found some time to test the GaudiRun app and it seems to be working. Thanks @alexpearce! (Should I close this now, or is that your job?)

**Comment by alexpearce** [comment]
You go ahead 😄

**Comment by bixel** [comment]
😄
